### ISSUE TITLE
Some users are not initalizing steam correctly (Possibly related to visual studio install)

### ISSUE THREAD

**Issue by ajrdesign** [YoYoGames/GMEXT-Steamworks#10]
Context: https://forum.gamemaker.io/index.php?threads/steam-does-not-initialize-without-visual-studio-installed.101528/#post-613107

I've verified an issue with the >1.2 versions of the extension. Steam is initializing for some users but not others. The developer in the post has identified that it has something to do with visual studio.

FYI it seems to be working fine for the previous version.

**Comment by rwkay** [comment]
Could this be to do with the version of Visual Studio that we have compiled the extension with @DiasFranciscoA can you please confirm which version of Visual Studio the extension was built with as the C runtime library  for that will need to be a dependency setup on Steam.

**Comment by DiasFranciscoA** [comment]
@rwkay I've checked the binaries and the current ones do seem to be Debug versions.

@ajrdesign A new binary was just updated to the main branch (you can try it already). we should be ready to update the marketplace one tomorrow.

**Comment by ajrdesign** [comment]
@DiasFranciscoA Hey I'm not seeing a new version on the marketplace or an updated release here.

**Comment by DiasFranciscoA** [comment]
Both marketplace and github releases were updated.

**Comment by pyrohair** [comment]
The Marketplace build seems to import into GM fine, but today's v1.2.2 updated release can't be imported. On import, it locks up GM and a force-quit is required. Digging further, I tried to load up the GM project from the Source Code release (Steamworks.yyp, after extracting) and it just goes to the standard GM Start Page instead of loading the project. Manually selecting "Open" and navigating to the .yyp file, on load I get the error:

"Project load failed. Unable to load [path_to_project]\Steamworks.yyp"

Unless I'm doing something wrong, it seems there may still be an issue with the Github release.

**Comment by pyrohair** [comment]
@DiasFranciscoA Yup, the v1.2.3 release can now be successfully imported. Thanks for pushing that.

**Comment by L-Clouds** [comment]
I think this has reoccurred with 1.3.0 - players with Visual Studio installed are having steam initialize, and players who have only the redist are not.
