### ISSUE TITLE
Achievements/Stats API non-functional

### ISSUE THREAD

**Issue by januaryonline** [YoYoGames/GMEXT-Steamworks#110]
Project ran from IDE cannot give achievements or write/request user statistics anymore. Possibly due to RequestCurrentStats change introduced in SDK 1.61?

**Comment by DiasFranciscoA** [comment]
SDK version 1.61 is now required for version 2.1.0, there was a lock in place that would not allow the compilation the lock has been updated now (refer to the hotfix just released)

**Comment by januaryonline** [comment]
Hello,

Thank you for the quick hotfix - compilation is now possible but Achievements & Stats still don't seem to function...
Neither requesting global stats, or getting & setting achievements seem to do anything. I am also not able to reset user statistics & achievements anymore.

**Comment by tabularelf** [comment]
Can confirm. Only seems like from the Steamworks extension example, just `+1 Win` actually gets you any achievement. The rest of the buttons do not function.

Also the Steamworks repository seems to have some older changes that the release change from yesterday had, not available on the repo. (Wasn't a huge deal for me to workaround, but felt like I should note that since the hash check was failing.)
