### ISSUE TITLE
[FEATURE REQUEST] [DOCUMENTATION]

### ISSUE THREAD

**Issue by 1-800-thewolf** [YoYoGames/GMEXT-Steamworks#52]
There doesn't seem to be any documentation on several functions such as the following:

- steam_request_global_achievement_percentages
- steam_get_global_stat

I'd like to know the syntax for these functions along with other steam-related functions. I'd also like examples of how these functions are used.

Thanks!

**Comment by 1-800-thewolf** [comment]
Another function I need information about is steam_get_achievement_achieved_percent. I don't see where to find how to use it properly.

**Comment by aconeishone** [comment]
I agree

**Comment by AragornJual** [comment]
Just hit f1 when you select the function and it will pull up the manual including examples of how to use the functions. You don't need to go posting on the github page just because you don't know how to push a button. Please just try anything first before posting publicly next time.

**Comment by tabularelf** [comment]
> Just hit f1 when you select the function and it will pull up the manual including examples of how to use the functions. You don't need to go posting on the github page just because you don't know how to push a button. Please just try anything first before posting publicly next time.

You do realize that extensions do not in fact, bring up the correct manual page?

**Comment by AragornJual** [comment]
No, Game Maker has built-in Steam functions. You can just read the manual. Besides, if the function works, just use it. You don't need someone to hold your hand every step of the way explaining how it works. Just Google it.

**Comment by tabularelf** [comment]
> No, Game Maker has built-in Steam functions. You can just read the manual. Besides, if the function works, just use it. You don't need someone to hold your hand every step of the way explaining how it works. Just Google it.

The "built-in Steam functions" were removed ages ago and put into an extension... I do get that sometimes you want someone to actually put in the work, but prior to the closing of #54 , that already makes it very hard for the average user to even utilize something that was otherwise broken. Granted, it being fixed now means that it's now possible to use... But not having something documented doesn't mean that one should be forced to look through the source code, some people do not genuinely know how to put functions together, whether that's down to being new or not.

I know from both helping people with GameMaker, as well as building and maintaining not just mine, but others libraries.

**Comment by 1-800-thewolf** [comment]
@YYBartT I really appreciate all this documentation and the examples. I'm attempting to use the steam_request_global_stats function as demonstrated in your example. It never triggers the Steam Async event.

steam_initialised returns **true**.
steam_stats_ready returns **true**.
steam_request_global_stats returns **true**
steam_get_stat_int returns **6** which is the correct value for 1 user but is not the total aggregated value.
The Steam Async event never triggers and I never see the show_debug_message("{0}: {1}", _type, _success) report.

I've given it 30+ minutes and still never triggers the async event. Is there something different that needs to be done to successfully retrieve global stats?
