### ISSUE TITLE
Issues with my game's app ID

### ISSUE THREAD

**Issue by aconeishone** [YoYoGames/GMEXT-Steamworks#55]
When running the game and trying to display my game's app ID via steam_get_app_id() displays "undefined" everything works like achievements and such, but lobbies for some reason can only count 1 player being in them even if there are more than 1 players inside the lobby

**Comment by stuckie** [comment]
Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue to ensure we see exactly what you see and then learn why this problem is caused.

Please report this issue again, but ensure you have a suitable project open at the time you open the bug reporter and that you allow GameMaker to include the project.

Thanks!

[Why Have You Asked Me For A Sample?](https://help.gamemaker.io/hc/en-us/articles/13150754375453#h_01J15CZA1TP1FH04XQE2P18AAG)
